#!/bin/bash

#SBATCH --job-name=lidc-idri-download # Job name
#SBATCH --output=/home/caap/Thesis-Synthex/jobs/slurm/logs/lidc-idri-download.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule 8 cores (includes hyperthreading)
#SBATCH --time=12:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=brown    # Run on either the Red or Brown queue
#SBATCH --mail-type=FAIL,END

python3 /home/caap/Thesis-Synthex/data/lidc-idri-ct.py